<?php
/**
 * Plugin Name: SA Tax Calculator
 * Description: South Africa income tax calculator
 * Version: 2.1
 */

if (!defined('ABSPATH')) {
    exit;
}

/**
 * Default settings
 */
function satc_get_default_settings() {
    return array(
        'brand_primary'        => '#163a5f',
        'brand_primary_dark'   => '#102c49',
        'brand_accent'         => '#c8a24a',
        'brand_accent_dark'    => '#a78334',
        'brand_highlight'      => '#2f7dbd',
        'brand_danger'         => '#c44b3d',

        'uif_rate'             => '0.01',
        'uif_monthly_cap'      => '177.12',

        'threshold_under65'    => '95750',
        'threshold_65to74'     => '148217',
        'threshold_75plus'     => '165689',

        'rebate_under65'       => '17235',
        'rebate_65to74'        => '26679',
        'rebate_75plus'        => '29824',

        'medical_credit_first'      => '364',
        'medical_credit_second'     => '364',
        'medical_credit_additional' => '246',

        'pdf_logo_url'         => '',
        'pdf_company_name'     => 'Tax Consulting South Africa',
        'pdf_footer_text'      => 'Generated by the SA Tax Calculator',
        'pdf_disclaimer_title' => 'Assumptions and Disclaimer',
        'pdf_disclaimer_body'  => 'This calculator provides an estimate only. It is based on simplified PAYE logic, UIF, retirement contributions, and medical tax credits. It does not replace payroll software, SARS guidance, or professional tax advice. Additional remuneration items, fringe benefits, travel allowances, bonuses, and specific employer rules may affect actual results.',
    );
}

/**
 * Get merged settings
 */
function satc_get_settings() {
    $saved = get_option('satc_settings', array());
    return wp_parse_args($saved, satc_get_default_settings());
}

/**
 * Sanitize settings
 */
function satc_sanitize_settings($input) {
    $defaults = satc_get_default_settings();
    $output = array();

    $color_fields = array(
        'brand_primary',
        'brand_primary_dark',
        'brand_accent',
        'brand_accent_dark',
        'brand_highlight',
        'brand_danger',
    );

    foreach ($color_fields as $field) {
        $output[$field] = isset($input[$field]) ? sanitize_hex_color($input[$field]) : $defaults[$field];

        if (empty($output[$field])) {
            $output[$field] = $defaults[$field];
        }
    }

    $number_fields = array(
        'uif_rate',
        'uif_monthly_cap',
        'threshold_under65',
        'threshold_65to74',
        'threshold_75plus',
        'rebate_under65',
        'rebate_65to74',
        'rebate_75plus',
        'medical_credit_first',
        'medical_credit_second',
        'medical_credit_additional',
    );

    foreach ($number_fields as $field) {
        $output[$field] = isset($input[$field]) ? (string) floatval($input[$field]) : $defaults[$field];
    }

    $text_fields = array(
        'pdf_company_name',
        'pdf_footer_text',
        'pdf_disclaimer_title',
    );

    foreach ($text_fields as $field) {
        $output[$field] = isset($input[$field]) ? sanitize_text_field($input[$field]) : $defaults[$field];
    }

    $output['pdf_logo_url'] = isset($input['pdf_logo_url']) ? esc_url_raw($input['pdf_logo_url']) : $defaults['pdf_logo_url'];

    $output['pdf_disclaimer_body'] = isset($input['pdf_disclaimer_body'])
        ? wp_kses_post($input['pdf_disclaimer_body'])
        : $defaults['pdf_disclaimer_body'];

    return $output;
}

/**
 * Register settings
 */
function satc_register_settings() {
    register_setting(
        'satc_settings_group',
        'satc_settings',
        array(
            'type'              => 'array',
            'sanitize_callback' => 'satc_sanitize_settings',
            'default'           => satc_get_default_settings(),
        )
    );
}
add_action('admin_init', 'satc_register_settings');

/**
 * Add admin menu page
 */
function satc_add_settings_page() {
    add_options_page(
        'SA Tax Calculator Settings',
        'SA Tax Calculator',
        'manage_options',
        'satc-settings',
        'satc_render_settings_page'
    );
}
add_action('admin_menu', 'satc_add_settings_page');

/**
 * Render standard input field
 */
function satc_render_input_field($name, $label, $type = 'text', $step = '0.01') {
    $settings = satc_get_settings();
    $value = isset($settings[$name]) ? $settings[$name] : '';

    echo '<tr>';
    echo '<th scope="row"><label for="' . esc_attr($name) . '">' . esc_html($label) . '</label></th>';
    echo '<td>';
    echo '<input type="' . esc_attr($type) . '" id="' . esc_attr($name) . '" name="satc_settings[' . esc_attr($name) . ']" value="' . esc_attr($value) . '" class="regular-text" ' . ($type === 'number' ? 'step="' . esc_attr($step) . '"' : '') . ' />';
    echo '</td>';
    echo '</tr>';
}

/**
 * Render textarea field
 */
function satc_render_textarea_field($name, $label, $rows = 6) {
    $settings = satc_get_settings();
    $value = isset($settings[$name]) ? $settings[$name] : '';

    echo '<tr>';
    echo '<th scope="row"><label for="' . esc_attr($name) . '">' . esc_html($label) . '</label></th>';
    echo '<td>';
    echo '<textarea id="' . esc_attr($name) . '" name="satc_settings[' . esc_attr($name) . ']" rows="' . esc_attr($rows) . '" class="large-text">' . esc_textarea($value) . '</textarea>';
    echo '</td>';
    echo '</tr>';
}

/**
 * Render settings page
 */
function satc_render_settings_page() {
    if (!current_user_can('manage_options')) {
        return;
    }
    ?>
    <div class="wrap">
        <h1>SA Tax Calculator Settings</h1>
        <p>Update brand colours, tax values, and PDF branding without editing plugin code.</p>

        <form method="post" action="options.php">
            <?php settings_fields('satc_settings_group'); ?>

            <h2>Brand Colours</h2>
            <table class="form-table" role="presentation">
                <?php
                satc_render_input_field('brand_primary', 'Primary Colour', 'text');
                satc_render_input_field('brand_primary_dark', 'Primary Dark Colour', 'text');
                satc_render_input_field('brand_accent', 'Accent Colour', 'text');
                satc_render_input_field('brand_accent_dark', 'Accent Dark Colour', 'text');
                satc_render_input_field('brand_highlight', 'Highlight Colour', 'text');
                satc_render_input_field('brand_danger', 'Danger Colour', 'text');
                ?>
            </table>

            <h2>UIF Settings</h2>
            <table class="form-table" role="presentation">
                <?php
                satc_render_input_field('uif_rate', 'UIF Rate', 'number', '0.0001');
                satc_render_input_field('uif_monthly_cap', 'UIF Monthly Cap', 'number', '0.01');
                ?>
            </table>

            <h2>Tax Thresholds</h2>
            <table class="form-table" role="presentation">
                <?php
                satc_render_input_field('threshold_under65', 'Threshold Under 65', 'number', '0.01');
                satc_render_input_field('threshold_65to74', 'Threshold 65 to 74', 'number', '0.01');
                satc_render_input_field('threshold_75plus', 'Threshold 75+', 'number', '0.01');
                ?>
            </table>

            <h2>Rebates</h2>
            <table class="form-table" role="presentation">
                <?php
                satc_render_input_field('rebate_under65', 'Rebate Under 65', 'number', '0.01');
                satc_render_input_field('rebate_65to74', 'Rebate 65 to 74', 'number', '0.01');
                satc_render_input_field('rebate_75plus', 'Rebate 75+', 'number', '0.01');
                ?>
            </table>

            <h2>Medical Tax Credits</h2>
            <table class="form-table" role="presentation">
                <?php
                satc_render_input_field('medical_credit_first', 'First Member Monthly Credit', 'number', '0.01');
                satc_render_input_field('medical_credit_second', 'Second Member Monthly Credit', 'number', '0.01');
                satc_render_input_field('medical_credit_additional', 'Additional Member Monthly Credit', 'number', '0.01');
                ?>
            </table>

            <h2>PDF Branding</h2>
            <table class="form-table" role="presentation">
                <?php
                satc_render_input_field('pdf_logo_url', 'PDF Logo URL', 'text');
                satc_render_input_field('pdf_company_name', 'PDF Company Name', 'text');
                satc_render_input_field('pdf_footer_text', 'PDF Footer Text', 'text');
                satc_render_input_field('pdf_disclaimer_title', 'PDF Disclaimer Title', 'text');
                satc_render_textarea_field('pdf_disclaimer_body', 'PDF Disclaimer Body', 8);
                ?>
            </table>

            <?php submit_button('Save Settings'); ?>
        </form>
    </div>
    <?php
}

/**
 * Save PDF to Media Library
 */
function satc_save_pdf_to_media() {
    check_ajax_referer('satc_pdf_nonce', 'nonce');

    if (empty($_POST['pdf_base64'])) {
        wp_send_json_error(array('message' => 'No PDF data received.'));
    }

    $pdf_base64 = wp_unslash($_POST['pdf_base64']);
    $file_name  = !empty($_POST['file_name']) ? sanitize_file_name(wp_unslash($_POST['file_name'])) : 'sa-tax-summary.pdf';

    if (strpos($pdf_base64, 'base64,') !== false) {
        $pdf_base64 = substr($pdf_base64, strpos($pdf_base64, 'base64,') + 7);
    }

    $pdf_binary = base64_decode($pdf_base64);

    if ($pdf_binary === false) {
        wp_send_json_error(array('message' => 'PDF decoding failed.'));
    }

    $upload = wp_upload_bits($file_name, null, $pdf_binary);

    if (!empty($upload['error'])) {
        wp_send_json_error(array('message' => $upload['error']));
    }

    $filetype = wp_check_filetype($upload['file'], null);

    $attachment = array(
        'post_mime_type' => $filetype['type'] ? $filetype['type'] : 'application/pdf',
        'post_title'     => sanitize_text_field(pathinfo($file_name, PATHINFO_FILENAME)),
        'post_content'   => '',
        'post_status'    => 'inherit',
    );

    $attachment_id = wp_insert_attachment($attachment, $upload['file']);

    if (is_wp_error($attachment_id) || !$attachment_id) {
        wp_send_json_error(array('message' => 'Attachment could not be created.'));
    }

    update_attached_file($attachment_id, $upload['file']);

    wp_send_json_success(array(
        'message'       => 'PDF saved successfully.',
        'attachment_id' => $attachment_id,
        'url'           => $upload['url'],
    ));
}
add_action('wp_ajax_satc_save_pdf_to_media', 'satc_save_pdf_to_media');
add_action('wp_ajax_nopriv_satc_save_pdf_to_media', 'satc_save_pdf_to_media');

/**
 * Enqueue assets
 */
function satc_enqueue_assets() {
    wp_enqueue_style(
        'satc-style',
        plugin_dir_url(__FILE__) . 'assets/css/calculator.css',
        array(),
        '2.2'
    );

    wp_enqueue_script(
        'satc-jspdf',
        plugin_dir_url(__FILE__) . 'assets/vendor/jspdf/jspdf.umd.min.js',
        array(),
        '2.5.1',
        true
    );

    wp_enqueue_script(
        'satc-script',
        plugin_dir_url(__FILE__) . 'assets/js/calculator.js',
        array('satc-jspdf'),
        '2.2',
        true
    );

    wp_localize_script(
        'satc-script',
        'satcSettings',
        satc_get_settings()
    );

    wp_localize_script(
        'satc-script',
        'satcAjax',
        array(
            'ajax_url' => admin_url('admin-ajax.php'),
            'nonce'    => wp_create_nonce('satc_pdf_nonce'),
        )
    );
}
add_action('wp_enqueue_scripts', 'satc_enqueue_assets');

/**
 * Render calculator
 */
function satc_render_calculator() {
    ob_start();
    ?>

    <div class="satc-wrapper">

        <h2>South Africa Income Tax Calculator</h2>

        <p class="satc-intro">
            Use this calculator to estimate your South African income tax based on your income period,
            age group, retirement contribution, and medical aid members.
        </p>

        <div class="satc-form">

            <div class="satc-field">
                <label for="satc-tax-year">Tax Year</label>
                <select id="satc-tax-year">
                    <option value="2026">2025 / 2026</option>
                </select>
            </div>

            <div class="satc-field">
                <label for="satc-income-period">
                    Income Period
                    <span class="satc-tooltip" tabindex="0">?
                        <span class="satc-tooltip-text">Choose whether the amount you enter is monthly income or annual income.</span>
                    </span>
                </label>
                <select id="satc-income-period">
                    <option value="annual">Annual Income</option>
                    <option value="monthly">Monthly Income</option>
                </select>
            </div>

            <div class="satc-field">
                <label for="satc-age-group">
                    Age Group
                    <span class="satc-tooltip" tabindex="0">?
                        <span class="satc-tooltip-text">Age affects both the tax threshold and the rebate applied to your calculation.</span>
                    </span>
                </label>
                <select id="satc-age-group">
                    <option value="under65">Under 65</option>
                    <option value="65to74">65 to 74</option>
                    <option value="75plus">75+</option>
                </select>
            </div>

            <div class="satc-field">
                <label for="satc-income">Income (R)</label>
                <input type="number" id="satc-income" value="350000" min="0" step="0.01">
            </div>

            <div class="satc-field">
                <label for="satc-retirement">
                    Retirement Contribution (%)
                    <span class="satc-tooltip" tabindex="0">?
                        <span class="satc-tooltip-text">This percentage is treated as a pre-tax retirement contribution that reduces taxable income.</span>
                    </span>
                </label>
                <input type="number" id="satc-retirement" value="0" min="0" step="0.1">
            </div>

            <div class="satc-field">
                <label for="satc-medical-members">
                    Medical Aid Members
                    <span class="satc-tooltip" tabindex="0">?
                        <span class="satc-tooltip-text">Count the taxpayer plus dependants covered. This affects the medical tax credit applied.</span>
                    </span>
                </label>
                <select id="satc-medical-members">
                    <option value="0">No medical aid</option>
                    <option value="1">1 member</option>
                    <option value="2">2 members</option>
                    <option value="3">3 members</option>
                    <option value="4">4 members</option>
                    <option value="5">5 members</option>
                    <option value="6">6 members</option>
                </select>
                <small class="satc-help-text">
                    Count the taxpayer plus dependants covered by the medical aid.
                </small>
            </div>

        </div>

        <div class="satc-actions" style="gap: 12px; flex-wrap: wrap;">
            <button type="button" class="satc-download-btn" id="satc-download-summary">
                Download PDF Summary
            </button>

            <button type="button" class="satc-download-btn" id="satc-save-summary">
                Save PDF to Media Library
            </button>
        </div>

        <div id="satc-save-message" style="margin-bottom: 20px; font-size: 14px;"></div>

        <div class="satc-results">
            <h3>Your Results</h3>

            <div class="satc-hero-grid">
                <div class="satc-hero-card satc-hero-card-main">
                    <span class="satc-hero-label">Your Payslip at a Glance</span>
                    <strong class="satc-hero-value" id="satc-monthly-net-hero">R0.00</strong>
                    <span class="satc-hero-subtext">Estimated Monthly Take-Home</span>
                </div>

                <div class="satc-hero-card">
                    <span class="satc-hero-label">Monthly PAYE</span>
                    <strong class="satc-hero-value" id="satc-monthly-paye-hero">R0.00</strong>
                    <span class="satc-hero-subtext">Estimated employees' tax</span>
                </div>

                <div class="satc-hero-card">
                    <span class="satc-hero-label">Monthly UIF</span>
                    <strong class="satc-hero-value" id="satc-monthly-uif-hero">R0.00</strong>
                    <span class="satc-hero-subtext">Estimated UIF deduction</span>
                </div>

                <div class="satc-hero-card">
                    <span class="satc-hero-label">Effective Tax Rate</span>
                    <strong class="satc-hero-value" id="satc-effective-tax-rate-hero">0.00%</strong>
                    <span class="satc-hero-subtext">PAYE as % of annual income</span>
                </div>
            </div>

            <div class="satc-results-grid">
                <div class="satc-breakdown-card">
                    <div class="satc-card-header">
                        <h4>Breakdown</h4>
                        <p>Quick salary and tax estimate</p>
                    </div>

                    <div class="satc-breakdown-list">
                        <div class="satc-breakdown-row"><span>Annual Income Used</span><strong id="satc-annual-income-used">R0.00</strong></div>
                        <div class="satc-breakdown-row"><span>Retirement Contribution</span><strong id="satc-retirement-amount">R0.00</strong></div>
                        <div class="satc-breakdown-row"><span>Taxable Income</span><strong id="satc-taxable-income">R0.00</strong></div>
                        <div class="satc-breakdown-row"><span>Tax Threshold Applied</span><strong id="satc-threshold-used">R0.00</strong></div>
                        <div class="satc-breakdown-row"><span>Medical Tax Credit (Monthly)</span><strong id="satc-medical-credit-monthly">R0.00</strong></div>
                        <div class="satc-breakdown-row"><span>Medical Tax Credit (Annual)</span><strong id="satc-medical-credit-annual">R0.00</strong></div>
                        <div class="satc-breakdown-row"><span>Annual PAYE</span><strong id="satc-annual-paye">R0.00</strong></div>
                        <div class="satc-breakdown-row"><span>Monthly PAYE</span><strong id="satc-monthly-paye">R0.00</strong></div>
                        <div class="satc-breakdown-row"><span>Monthly UIF</span><strong id="satc-monthly-uif">R0.00</strong></div>
                        <div class="satc-breakdown-row"><span>Total Annual Deductions</span><strong id="satc-total-annual-deductions">R0.00</strong></div>
                        <div class="satc-breakdown-row"><span>Effective Tax Rate</span><strong id="satc-effective-tax-rate">0.00%</strong></div>
                        <div class="satc-breakdown-row satc-breakdown-row-total"><span>Estimated Monthly Take-Home</span><strong id="satc-monthly-net">R0.00</strong></div>
                    </div>
                </div>

                <div class="satc-summary-card">
                    <div class="satc-card-header">
                        <h4>Tax Summary</h4>
                        <p>Structured view of the estimate</p>
                    </div>

                    <div class="satc-table-wrap">
                        <table class="satc-summary-table">
                            <thead>
                                <tr><th>Item</th><th>Value</th></tr>
                            </thead>
                            <tbody>
                                <tr><td>Annual Income Used</td><td id="satc-summary-annual-income-used">R0.00</td></tr>
                                <tr><td>Retirement Contribution</td><td id="satc-summary-retirement-amount">R0.00</td></tr>
                                <tr><td>Taxable Income</td><td id="satc-summary-taxable-income">R0.00</td></tr>
                                <tr><td>Tax Threshold Applied</td><td id="satc-summary-threshold-used">R0.00</td></tr>
                                <tr><td>Medical Tax Credit (Monthly)</td><td id="satc-summary-medical-credit-monthly">R0.00</td></tr>
                                <tr><td>Medical Tax Credit (Annual)</td><td id="satc-summary-medical-credit-annual">R0.00</td></tr>
                                <tr><td>Annual PAYE</td><td id="satc-summary-annual-paye">R0.00</td></tr>
                                <tr><td>Monthly PAYE</td><td id="satc-summary-monthly-paye">R0.00</td></tr>
                                <tr><td>Monthly UIF</td><td id="satc-summary-monthly-uif">R0.00</td></tr>
                                <tr><td>Total Annual Deductions</td><td id="satc-summary-total-annual-deductions">R0.00</td></tr>
                                <tr><td>Effective Tax Rate</td><td id="satc-summary-effective-tax-rate">0.00%</td></tr>
                                <tr class="satc-summary-total-row"><td>Estimated Monthly Take-Home</td><td id="satc-summary-monthly-net">R0.00</td></tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

        <div class="satc-content">
            <h3>How this calculator works</h3>
            <p>
                This calculator estimates South African PAYE using annualised income, age-based tax thresholds,
                retirement contributions, medical tax credits, and UIF.
            </p>

            <h3>Important note</h3>
            <p>
                This is a simplified estimator and not a substitute for payroll software or professional tax advice.
                It does not yet include every payroll scenario, fringe benefit, allowance, or advanced medical tax rule.
            </p>
        </div>
    </div>

    <?php
    return ob_get_clean();
}
add_shortcode('sa_tax_calculator', 'satc_render_calculator');
